import Config

# Configure database (optional - only needed if archiving is enabled)
config :fleet_lm, FleetLM.Repo,
  url: System.get_env("DATABASE_URL") || "ecto://postgres:postgres@localhost:5432/fleet_lm_dev",
  pool_size: 10,
  # Don't fail if DB is not available
  queue_target: 5000,
  queue_interval: 1000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fleet_lm, FleetLMWeb.Endpoint,
  # Bind to all interfaces for cluster testing to avoid localhost vs 127.0.0.1 issues
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lt062n815Ov+oxSxJuDkXPv/nBm2hmURv9zEBvtiBj30yeiRj2o10s/UWNTv1eGg"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"
config :logger, level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Use local PubSub for development (change to :redis for testing horizontal scaling)
config :fleet_lm, :pubsub_adapter, :local

# Slower flush interval in dev to keep messages in disk log longer for testing hot path
config :fleet_lm, :storage_flush_interval_ms, 500

# Tune agent dispatch engine for development benchmarks
config :fleet_lm,
  agent_dispatch_tick_ms: 25,
  agent_debounce_window_ms: 250
