import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# No static assets are built/served by this API-only app,
# so disable static manifest warmup in prod.
# If a web UI is added later, re-enable with:
# config :fleet_lm, FleetLMWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Use local PubSub (pg2) in production; clustering handled via libcluster DNS
config :fleet_lm, :pubsub_adapter, :local

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
